version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always
    secrets:
      - postgres_password

  app:
    build: .
    depends_on:
      - db
    networks:
      - backend
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - backend

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

networks:
  backend: